### ISSUE TITLE
You can not store byte sequences in the environment 

### ISSUE THREAD

**Issue by jmz-b** [UoW-CPC/Asclepios-TrustedAuthority#3]
Just found [these lines ](https://github.com/UoW-CPC/Asclepios-TrustedAuthority/blob/master/dev.env#L8-L11)in the `dev.env` file:

```
KEY_G=b"123"
SALT=b"abc123!?"
IV=b"abcdefg"
```

and [these corresponding lines](https://github.com/UoW-CPC/Asclepios-TrustedAuthority/blob/master/parameters.py#L5-L8) in `parameters.py`

```
KeyG = os.getenv("KEY_G",b"123")
SALT = os.getenv("SALT",b"abc123!?")
IV = os.getenv("IV",b"abcdefg")
```

This will not work the way you expect, you can not store byte sequences directly in the environment like this.

for example:

```sh
$ export TEST=b"123"
$ python3
```

```py
>>> import os ; os.getenv("TEST")
'b123'
>>> type(os.getenv("TEST"))
<class 'str'>
>>> type(b"123")
<class 'bytes'>
```

as you can see, python gets the string value `b123` rather than the byte sequence `123` that is expected.

you need to store a plain string in the environment, and explicitly convert it to a byte sequence after it is loaded, for example:

```sh
export TEST="123"
$ python3
```

```py
>>> import os ; str.encode(os.getenv("TEST"))
b'123'
```

**Comment by hvandang** [comment]
Thanks. I updated parameters.py to resolve the issue.
