### ISSUE TITLE
You can not store python lists in the environment

### ISSUE THREAD

**Issue by jmz-b** [UoW-CPC/Asclepios-TrustedAuthority#4]
This is a very similar issue to my [previous PR](https://github.com/UoW-CPC/Asclepios-TrustedAuthority/issues/3)

In the `.env` files in this project, you define `ALLOWED_HOSTS` like this:

```sh
ALLOWED_HOSTS=['*']
```

but when this is loaded into python with `os.getenv` [in `settings.py`](https://github.com/UoW-CPC/Asclepios-TrustedAuthority/blob/master/TA/settings.py#L29) the value `os.getenv`  returns will be a string, as shown below:

```sh
root@dd49230e2214:/srv/TA# ./manage.py shell
```

```py
>>> from django.conf import settings
>>> settings.ALLOWED_HOSTS
"['*']"
>>> type(settings.ALLOWED_HOSTS)
<class 'str'>
```

Now this does not cause a problem if the value is `"['*']"`. Since python strings are iterable like lists, with each item being one character. So as far as django is concerned, you provided it a list which looks like this: `[ '"', '[', ''', '*', ''', ']', '"' ]`. One of the values in this list is `*`, so all hosts are allowed.

But there will be a problem if the value is something like `"['localhost', '192.0.2.10']"`.
Django will iterate over the string assuming each character is a separate host, so nothing will be allowed.

To overcome this, you need to do something like this in the `.env` files:

```sh
ALLOWED_HOSTS="localhost 192.0.2.10"
```

and something like this in settings.py:

```py
>>> os.getenv('ALLOWED_HOSTS').split(' ')
['localhost', '192.0.2.10']
```

This is a common mistake, and there [is an open issue](https://code.djangoproject.com/ticket/29606) on the django bug tracker about adding some type validation, but unfortunately it is still open.

**Comment by hvandang** [comment]
Thanks. I updated settings.py and deploy.env to resolve the issue.

**Comment by jmz-b** [comment]
@hvandang 

you still need to make this line `os.getenv('ALLOWED_HOSTS').split(' ')` to make it a list:

https://github.com/UoW-CPC/Asclepios-TrustedAuthority/blob/92db94d9ad86d696c98cd9bb97882e4db7e98c1b/TA/settings.py#L29

**Comment by hvandang** [comment]
@jmz-b 

I have updated
